### ISSUE TITLE
Allow to Collapse Blocks

### ISSUE THREAD

**Issue by boppy** [meanmail-dev/nginx-intellij-plugin#1]
**Is your feature request related to a problem? Please describe.**
Long config files lack the possibility to get an easy overview of different config directives.

**Describe the solution you'd like**
In long(er) config files, it would be great to have the possibility to collapse blocks from `{` to `}`, so you could easily check all existing locations (for example)

**Describe alternatives you've considered**
The only alternative (I see) would be to migrate every block into a file that is included into the config.

**Comment by meanmail** [comment]
Collapse Blocks feature added. The new version is available for download
