### ISSUE TITLE
Plugin doesn't work with EAP 2022.1

### ISSUE THREAD

**Issue by bigjoky** [meanmail-dev/nginx-intellij-plugin#11]
Good evening,

I looked for this issue but is not registered yet.

I'm working with the WebStorm EAP 2022.1 version and the plugin is not recognised, requires the IDE build 213 as this image below.

<img width="404" alt="Captura de pantalla 2022-01-31 a las 16 21 48" src="https://user-images.githubusercontent.com/4026060/151820790-87a45dc4-8638-4332-8c2c-7dadb87e264e.png">

**Comment by KeithTt** [comment]
Incompatible after upgrade to 2022.2.

![image](https://user-images.githubusercontent.com/15189954/181231777-26644da0-6500-4b7e-ad9c-27e9656a8b6c.png)
