### ISSUE TITLE
Plugin doesn't work with IntelliJ IDEA 2022.2

### ISSUE THREAD

**Issue by gsusI** [meanmail-dev/nginx-intellij-plugin#12]
Not reported yet, but it's not compatible with the latest release of IntelliJ IDEA, 2022.2

![image](https://user-images.githubusercontent.com/4558016/183112290-58f14104-1ef0-4808-ac7d-42ff33e7292e.png)

![image](https://user-images.githubusercontent.com/4558016/183112342-74c5483c-2bc4-489b-928f-9926ddcdc426.png)

**Comment by shokhaa** [comment]
+ PHPStrom

**Comment by alosultan** [comment]
I have the same problem: Plugin 'Nginx Configuration' (version '2021.3-2022.1') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is PY-222.3345.131

**Comment by jdswed** [comment]
I have the same problem, with all my IDES

**Comment by sbakic** [comment]
The only plugin that doesn't support the latest version. Will someone work on this at some point?

**Comment by truemoroz** [comment]
same problem

**Comment by meanmail** [comment]
The new plugin version was sent for moderation on October 9th. Moderation may take up to two business days. After that, the plugin will be available for download.
