### ISSUE TITLE
`ssl_certificate_by_lua_block` and `set_by_lua_block` directives not supported

### ISSUE THREAD

**Issue by aavshr** [meanmail-dev/nginx-intellij-plugin#16]
**Describe the bug**
`ssl_certificate_by_lua_block` and `set_by_lua_block` directives are not supported

**To Reproduce**
1. Use either of `ssl_certificate_by_lua_block` or `set_by_lua_block` and write lua. 

**Expected behavior**
Lua injection should be supported for these directives as well.

**Screenshots**
<img width="922" alt="Screenshot 2023-04-14 at 18 08 23" src="https://user-images.githubusercontent.com/22456204/232099485-261cf4c1-2ad6-4dc0-b22d-862b21918e37.png">

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Darwin 20.6.0
 - Product: GoLand
 - Version: 2021.2.3
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version: 2022.1.1

**Comment by meanmail** [comment]
@aavshr Support for these directives was added in version 2024.2
