### ISSUE TITLE
lack of support for `set_by_lua_block $foo` blocks

### ISSUE THREAD

**Issue by beetrootpaul** [meanmail-dev/nginx-intellij-plugin#18]
**Describe the bug**

`set_by_lua_block $foo` syntax is not supported

**To Reproduce**

Use a snippet like this:

```nginx
set $foo "";
set_by_lua_block $foo {
  -- potentially some interesting logic here instead of just the simple return below
  return "bar"
}
```

**Expected behavior**

Lua injection should be detected for this `set_by_lua_block`

**IDE:**
 - OS: macOS 14.5
 - Product: WebStorm
 - Version 2024.1.5

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2024.3

**Additional context**

I lack know-how about nginx and Lua. I use `set_by_lua_block $foo { … }` syntax, because it is already present in files I have to work on. I might just not know about some alternative idiomatic approach of setting nginx vars out of Lua blocks.

**Comment by meanmail** [comment]
Thank you for reporting this issue! We have implemented a fix for `set_by_lua_block` directives with parameters. The update will be released in the coming days (expected within this week). 

Changes include:
- Updated lexer to handle Lua block directive parameters
- Fixed syntax highlighting for Lua block directives
- Improved parsing of `set_by_lua_block` syntax

Stay tuned for the upcoming release! 🚀
