### ISSUE TITLE
`init_by_lua_block` `init_worker_by_lua_block` and `balancer_by_lua_block` directives not supported

### ISSUE THREAD

**Issue by O3cheng** [meanmail-dev/nginx-intellij-plugin#20]
**Describe the bug**
`init_by_lua_block` `init_worker_by_lua_block` and `balancer_by_lua_block` `header_filter_by_lua_block` `body_filter_by_lua_block` `log_by_lua_block` directives not supported

**To Reproduce**
Use either of `init_by_lua_block` `init_worker_by_lua_block` or `balancer_by_lua_block` `header_filter_by_lua_block` `body_filter_by_lua_block` `log_by_lua_block` and write lua.

**Expected behavior**
Lua injection should be supported for these directives as well.

**Screenshots**
![image](https://github.com/user-attachments/assets/c572c728-62dc-47e5-8dae-4a35ad5bcfb5)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Windows 11
 - Product: GoLand
 - Version: 2024.3
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2024.3

**Additional context**
Version 2024.3

**Comment by meanmail** [comment]
Thank you for bringing this to our attention! We have already implemented support for `init_by_lua_block`, `init_worker_by_lua_block`, and `balancer_by_lua_block` directives. The fix will be available in the upcoming plugin update.

We highly value your contribution to improving the plugin and appreciate your attention to detail. Stay tuned for updates!
