### ISSUE TITLE
Not working on PhpStorm 2021.1

### ISSUE THREAD

**Issue by fijas** [meanmail-dev/nginx-intellij-plugin#4]
**Describe the bug**
Not working on the newer 2021.1 version of PhpStorm

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Arch Linux
 - Product: PhpStorm
 - Version 2021.1
 - JRE Version: Built in version
 - Project SDK: -

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2020.2.1-203

**Additional context**
Not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PS-211.6693.120

**Comment by meanmail** [comment]
PhpStorm 2021.1 compatible version released. Available for download in two business days

**Comment by cowboy-cod3r** [comment]
Same with Intellij 2021.1

**Comment by meanmail** [comment]
New version available for download
