### ISSUE TITLE
Go to include files

### ISSUE THREAD

**Issue by twwd** [meanmail-dev/nginx-intellij-plugin#6]
**Is your feature request related to a problem? Please describe.**
I use plenty of include statements in my configuration files. Unfortunately it is very cumbersome to get to the corresponding files.

**Describe the solution you'd like**
I would like to be able to get to the included file via the _Go To_ functionality (Ctrl + Click, Ctrl + B).

**Comment by meanmail** [comment]
This feature is implemented in the current version of the plugin

**Comment by twwd** [comment]
For me, it does only work with paths relative to the file that uses the include (e.g. `../snippets/security/hsts.conf`) and not with paths relative to the config dir (e.g. `snippets/security/hsts.conf`).

**Comment by meanmail** [comment]
Thank you for reporting this issue! The fix has been implemented and will be available in version 2024.5. Now the plugin correctly handles paths relative to both the current file and the nginx root directory (the directory containing nginx.conf).
