### ISSUE TITLE
nginx.conf 有代码提示不？

### ISSUE THREAD

**Issue by wangtaicheng** [meanmail-dev/nginx-intellij-plugin#9]
如题， 编写配置的时候有代码提示不？

**Comment by meanmail** [comment]
代碼提示尚未實現，但肯定會出現在未來版本中。

**Comment by wangtaicheng** [comment]
> 代碼提示尚未實現，但肯定會出現在未來版本中。

https://github.com/ishchenko/idea-nginx 看这个项目，

**Comment by meanmail** [comment]
该插件实现了自动完成功能。未来有计划进行改进
